language: python

python:
  - "2.7"

env:
  - DJANGO_VERSION=1.8

install:
  - pip install -r requirements.txt --use-mirrors
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
  - pip install coveralls

script:
  - coverage run --source=RealEstate, python manage.py test

after_success:
  coveralls

notifications:
  slack: pdx-capstone:IFvGLq7Mzb30ho8B0QBqp3rk