language: python

python:
    - "2.7"

env:
    - DJANGO_VERSION=1.3.1
    - DJANGO_VERSION=1.4

install:
    - pip install -r requirements.txt --use-mirrors
    - pip install -q Django==$DJANGO_VERSION --use-mirrors
    - pip install -q https://github.com/praekelt/django-setuptest/archive/f4eacb4a929cdcc853a5c053c282dada5bdedc99.tar.gz --use-mirrors

script:
    - python manage.py test